spring.application.name=Ecotrace
spring.datasource.url=jdbc:postgresql://localhost:5432/mca
spring.datasource.name=mca
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Cutm@059
spring.jpa.hibernate.ddl-auto=update
server.port=8080